### ISSUE TITLE
Product line-wide consistency

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/paper-elements#57]
- [ ] Make font application consistent across elements (https://github.com/PolymerElements/paper-toast/pull/24)
- [ ] Make attribute vs. class usage consistent (https://github.com/PolymerElements/paper-elements/issues/23)

**Comment by notwaldorf** [comment]
Notes: for the font-consistency item, https://github.com/PolymerElements/paper-styles/pull/80 should get us most of the way there. If all the elements would just use the mixins defined in `typography.html`, vs using their own, then changing the font across all paper elements is just a css selector

``` css
<style is="custom-style">
    :root {
      --paper-font-common-base: {
        font-family: serif !important;
      };
    };
</style>
```
