### ISSUE TITLE
Create CSS coding style guidelines

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-elements#69]
I want to propose create a CSS coding style guidelines to PolymerElements.

Maybe something like [CSScomb](http://csscomb.com)?
This tool sort the CSS by the property type: position, display, sizing, etc...

Example with `paper-fab`:

Before:

``` css
:host {
  @apply(--layout-vertical);
  @apply(--layout-center-center);

  background: var(--paper-fab-background, --accent-color);
  border-radius: 50%;
  box-sizing: border-box;
  color: var(--text-primary-color);
  cursor: pointer;
  height: 56px;
  min-width: 0;
  outline: none;
  padding: 16px;
  position: relative;
  -moz-user-select: none;
  -ms-user-select: none;
  -webkit-user-select: none;
  user-select: none;
  width: 56px;
  z-index: 0;

  /* NOTE: Both values are needed, since some phones require the value `transparent`. */
  -webkit-tap-highlight-color: rgba(0,0,0,0);
  -webkit-tap-highlight-color: transparent;

  @apply(--paper-fab);
}
```

After:

``` css
:host {
  position: relative;
  z-index: 0;

  @apply(--layout-vertical);
  @apply(--layout-center-center);

  box-sizing: border-box;
  width: 56px;
  min-width: 0;
  height: 56px;
  padding: 16px;

  cursor: pointer;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;

  color: var(--text-primary-color);
  border-radius: 50%;
  outline: none;
  background: var(--paper-fab-background, --accent-color);

  /* NOTE: Both values are needed, since some phones require the value `transparent`. */
  -webkit-tap-highlight-color: rgba(0,0,0,0);
  -webkit-tap-highlight-color: transparent;

  @apply(--paper-fab);
}
```

What do you think? :blush:
